labels = [
    'Live animals/fish',
    'Cereal grains',
    'Other ag prods.',
    'Animal feed',
    'Meat/seafood',
    'Milled grain prods.',
    'Other foodstuffs',
    'Alcoholic beverages',
    'Tobacco prods.',
    'Building stone',
    'Natural sands',
    'Gravel',
    'Nonmetallic minerals',
    'Metallic ores',
    'Coal',
    'Crude petroleum',
    'Gasoline',
    'Fuel oils',
    'NG and fossil products',
    'Basic chemicals',
    'Pharmaceuticals',
    'Fertilizers',
    'Chemical prods.',
    'Plastics/rubber',
    'Logs',
    'Wood prods.',
    'Newsprint/paper',
    'Paper articles',
    'Printed prods.',
    'Textiles/leather',
    'Nonmetal min. prods.',
    'Base metals',
    'Articles-base metal',
    'Machinery',
    'Electronics',
    'Motorized vehicles',
    'Transport equip.',
    'Precision instruments',
    'Furniture',
    'Misc. mfg. prods.',
    'Waste/scrap',
    'Mixed freight'
]
